server:
   port: 8082
spring:
  application:
    name: customer-service 
  # cloud:
  #   config:
  #     enabled: false 
#  config:
#    import: "optional:configserver:http://localhost:8888"  
